version: '3'

services:
  zookeeper:
    image: docker.arvancloud.ir/bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: docker.arvancloud.ir/bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  elasticsearch:
    image: docker.arvancloud.ir/elasticsearch:8.17.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  producer:
    build: ./producer-service
    environment:
      - API_URL=https://fakerapi.it/api/v2/texts?_quantity=100&_locale=fa_IR
      - KAFKA_BROKER=kafka:9092
      - TOPIC_NAME=faker_topic
    command: python -m app.main
    depends_on:
      - kafka 

  consumer:
    build: ./consumer-service
    environment:
      - KAFKA_BROKER=kafka:9092
      - TOPIC_NAME=faker_topic
      - ES_HOST=http://elasticsearch:9200
      - ES_INDEX=faker_index
    command: python -m app.main
    depends_on:
      - kafka
      - elasticsearch

  fastapi:
    build: ./fastapi-service
    ports:
      - "8000:8000"
    environment:
      - ES_HOST=http://elasticsearch:9200
      - ES_INDEX=faker_index
    command: >  
      uvicorn app.main:app 
      --host 0.0.0.0 
      --port 8000 
    depends_on:
      - elasticsearch

volumes:
  esdata: